Repository abnamrocoesd/Chromata, pull requests merged in 2018-05, with the labels that each got.

#13 [WIP] Feature/fix version
  .appcast.xml
  bump-version.rb
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#14 Add feature: focus on selected layer
  README.md
  chromata.sketchplugin/Contents/Sketch/fixColors.js
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#15 Feature/update readme
  README.md
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#16 Issue/fix appcast
  .appcast.xml
  bump-version.rb
Labels: enhancement

#17 Issue/fix manifest
  README.md
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: bug, enhancement

#18 Feature/bump version arguments parser
  README.md
  bump-version.rb
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#19 Fix getting color from a text with fill color
  README.md
  chromata.sketchplugin/Contents/Sketch/Sources/CHRLayer.js
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: bug

#20 Add sneak peak
  README.md
Labels: enhancement

#24 Feature/update metadata
  README.md
  bump-version.rb
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#28 Feature/navigate through rogue layers
  chromata.sketchplugin/Contents/Sketch/Commands/CommandsShared.js
  chromata.sketchplugin/Contents/Sketch/Commands/findAllRogueLayers.js
  chromata.sketchplugin/Contents/Sketch/Commands/moveToNextRogueLayer.js
  chromata.sketchplugin/Contents/Sketch/Commands/moveToPreviousRogueLayer.js
  chromata.sketchplugin/Contents/Sketch/Commands/registerPalette.js
  chromata.sketchplugin/Contents/Sketch/Core/CHRPalette.js
  chromata.sketchplugin/Contents/Sketch/Core/CHRRogueLayers.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRDocumentParser.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRLayerParser.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRPageParser.js
  chromata.sketchplugin/Contents/Sketch/Storage/CHRUserDefaults.js
  chromata.sketchplugin/Contents/Sketch/commands.js
  chromata.sketchplugin/Contents/Sketch/fixColors.js
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#29 Develop
  .appcast.xml
  README.md
  bump-version.rb
  chromata.sketchplugin/Contents/Sketch/Commands/CommandsShared.js
  chromata.sketchplugin/Contents/Sketch/Commands/findAllRogueLayers.js
  chromata.sketchplugin/Contents/Sketch/Commands/moveToNextRogueLayer.js
  chromata.sketchplugin/Contents/Sketch/Commands/moveToPreviousRogueLayer.js
  chromata.sketchplugin/Contents/Sketch/Commands/registerPalette.js
  chromata.sketchplugin/Contents/Sketch/Core/CHRPalette.js
  chromata.sketchplugin/Contents/Sketch/Core/CHRRogueLayers.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRDocumentParser.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRLayerParser.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRPageParser.js
  chromata.sketchplugin/Contents/Sketch/Storage/CHRUserDefaults.js
  chromata.sketchplugin/Contents/Sketch/commands.js
  chromata.sketchplugin/Contents/Sketch/fixColors.js
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#30 Feature/user defaults multiple files
  chromata.sketchplugin/Contents/Sketch/Storage/CHRUserDefaults.js
Labels: enhancement

#31 Develop
  .appcast.xml
  chromata.sketchplugin/Contents/Sketch/Storage/CHRUserDefaults.js
  chromata.sketchplugin/Contents/Sketch/manifest.json
Labels: enhancement

#33 Issue/get leaf layer by id from node layer group layer
  chromata.sketchplugin/Contents/Sketch/Parser/CHRLayerParser.js
  chromata.sketchplugin/Contents/Sketch/Parser/CHRPageParser.js
Labels: bug

#35 Issue/style colors
  chromata.sketchplugin/Contents/Sketch/Parser/CHRStyleParser.js
Labels: bug
